language: go

go:
  - 1.9

before_install: go get -u github.com/client9/misspell/cmd/misspell

install:
  - git clone https://github.com/junegunn/vader.vim.git tests/vader.vim
  - git clone https://github.com/vim/vim /tmp/vim
  - mkdir ~/bin
  - cd /tmp/vim
  - sudo apt-get install -y gettext libncurses5-dev libacl1-dev libgpm-dev
  - ./configure --with-features=huge --enable-fail-if-missing --enable-pythoninterp --prefix=$HOME/bin/vim
  - make && make install
  - git clone https://github.com/junegunn/vader.vim.git
  - export VIM_EXE=$HOME/bin/vim/bin/vim

before_script:
  - cd $HOME/build/heavenshell/vim-misspell/tests

script:
  - VIM_EXE=$HOME/bin/vim/bin/vim ./run.sh > /dev/null && echo Success || echo Fail
